name: Diagnostics .NET 9 ZBB Ad-Hoc

on:
  schedule:
  - cron: "0 4 * * 1"
  workflow_dispatch:

jobs:
  DiagnosticReportWeekly:
    uses: ./.github/workflows/generic-report-generator.yml
    with:
      configName: diagnostics-runtime-zbb9
      oldConfigDate: ${{ github.event.inputs.base_json_date }}