name: Diagnostics .NET 9 ZBB Ad-Hoc

on:
  workflow_dispatch:
    inputs:
      base_json_date:
        description: 'JSON cache date'
        required: true

jobs:
  DiagnosticReportWeekly:
    uses: ./.github/workflows/generic-report-generator.yml
    with:
      configName: diagnostics-runtime-zbb9
      oldConfigDate: ${{ github.event.inputs.base_json_date }}