# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  schedule:
  - cron: "0 6 * * 1"

permissions:
  issues: read
  contents: write
  actions: none
  checks: none
  deployments: none
  packages: none
  repository-projects: none

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: |
          file=$(find reports -maxdepth 1 -name '*.json' | sort -r | head -1) 
          dotnet run -c release -- config.json $file
          ls reports
        
