name: Diagnostics .NET Report Ad Hoc

on:
  workflow_dispatch:
    inputs:
      base_json_date:
        description: 'JSON cache date'
        required: false
jobs:
  DiagnosticReport:
    uses: ./.github/workflows/generic-report-generator.yml
    with:
      configName: diagnostics
      reportFolderRelativePath: diagnostics-reports
      oldConfigDate: ${{ github.event.inputs.base_json_date }}
