name: Issue Report Generator

on:
  workflow_call:
    inputs:
      configName:
        description: 'Base name of the config without json qualifier.'
        required: true
        type: string
      shouldUpdateCaches:
        description: 'Update caches. If checked, the run should update the readme and caches. Otherwise just generate the report.'
        required: false
        default: true
        type: boolean
      oldConfigDate:
        description: 'Optional. Name of the report in reportFolderRelativePath to use as the base cache report. If passed, results are only available as a pipeline artifact.'
        required: false
        type: string

permissions:
  issues: read
  contents: write
  actions: none
  checks: none
  deployments: none
  packages: none
  repository-projects: none

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - run: npm ci
    - name: Run report
      id: validate-inputs-gh
      uses: actions/github-script@v7
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        script: |
            const { default: generate_report } = await import('${{ github.workspace }}/.github/workflows/scripts/run-report-generator.js')
            await generate_report({core, exec})