name: Issue Report Generator

on:
  workflow_call:
    inputs:
        configName:
          required: true
          type: string
        # TODO: this could escape the root.
        reportFolderRelativePath:
          required: true
          type: string

permissions:
  issues: read
  contents: write
  actions: none
  checks: none
  deployments: none
  packages: none
  repository-projects: none

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: |
        echo "Using config: "Configs/${{ inputs.configName }}.json""
        file=$(find ${{ inputs.reportFolderRelativePath }} -maxdepth 1 -name '*.json' | sort -r | head -1)
        [ -z "$file" ] && echo "No cached result found."
        [ -n "$file" ] && echo "Using cached result: "$file""
        dotnet run -c release -- "Configs/${{ inputs.configName }}.json" "$file"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload Results
      run: |
        git add *reports
        git -c user.name="Report Generator" -c user.email="juan@hoyosjs.com" commit -m "Add report for diagnostics $(date +'%Y-%m-%d')"
        git push
